Repository MT-CTF/maps, pull requests merged in 2019-02, with the labels that each got.

#10 Add plain_battle by -sniper-
  10_plain_battle.conf
  10_plain_battle.mts
Labels: New map, Review required

#19 Update Plain battle map
  10_plain_battle.mts
Labels: Enhancement, Two approvals

#14 Add Forest by -sniper-
  forest_map.conf
  forest_map.mts
Labels: New map, Two approvals

#13 Add River Valley by -sniper-
  river_valley.conf
  river_valley.mts
Labels: New map, One approval, Two approvals
