Repository MT-CTF/maps, pull requests merged in 2019-07, with the labels that each got.

#22 Add "Karsthafen town" by solars, Peters and -sniper-
  17_karsthafen_town.conf
  17_karsthafen_town.mts
  17_karsthafen_town.png
Labels: New map, Two approvals

#36 Fix barrier bug in Karsthafen town map
  17_karsthafen_town.conf
  17_karsthafen_town.mts
Labels: Bug / Bugfix, One approval

#37 Improve The Wall Map
  13_wall.conf
  13_wall.mts
Labels: Enhancement, One approval

#40 16_hunting_season: Remove furnaces and doors
  16_hunting_season.mts
Labels: Bug / Bugfix, One approval
