Repository MT-CTF/maps, pull requests merged in 2019-10, with the labels that each got.

#57 Add 5 torches to Ice age map as spawn item
  04_iceage.conf
Labels: Enhancement, One approval, Review required

#46 Add Towers by Atmozpheric
  19_towers.conf
  19_towers.mts
  19_towers.png
Labels: New map, Two approvals

#59 remove doors and furnaces in "karsthafen bridge" map
  15_karsthafen_bridge.mts
Labels: Bug / Bugfix, Two approvals

#43 repair plain battle
  10_plain_battle.conf
  10_plain_battle.mts
  10_plain_battle.png
Labels: Enhancement, One approval

#61 Add more chests for Hunting season map
  16_hunting_season.conf
Labels: Enhancement, One approval, Review required

#62 fix heretic mistake
  18_abandoned_isles.conf
Labels: Enhancement, One approval, Review required

#45 Add Wool land
  20_wool_land.conf
  20_wool_land.mts
  20_wool_land.png
Labels: New map, Two approvals

#48 Add "Big Ocean" map by gameit
  21_big_ocean.conf
  21_big_ocean.mts
  21_big_ocean.png
Labels: New map, One approval, Review required

#64 Revert "Add "Big Ocean" map by gameit"
  21_big_ocean.conf
  21_big_ocean.mts
  21_big_ocean.png
Labels: One approval
