Repository MT-CTF/maps, pull requests merged in 2020-12, with the labels that each got.

#161 Nether kingdom: move the bases closer together
  nether_kingdom/map.conf
  nether_kingdom/screenshot.png
Labels: Enhancement, One approval :heavy_check_mark:

#162 Revert "Bridge map: Move red base to better position (#145)" commit
  bridge/map.conf
  bridge/screenshot.png
Labels: Review required

#128 Mini Village Map
  mini_village/map.conf
  mini_village/map.mts
  mini_village/screenshot.png
Labels: New map, One approval :heavy_check_mark:

#168 New Map "Lava Puddles" by smugler5
  lava_puddles/map.conf
  lava_puddles/map.mts
  lava_puddles/screenshot.png
Labels: New map, One approval :heavy_check_mark:

#167 Add new "Pyramids of Ahkmenrah" map by Darkf4antom and SoulSeeker
  ahkmenrah_pyramids/map.conf
  ahkmenrah_pyramids/map.mts
  ahkmenrah_pyramids/screenshot.png
Labels: New map, One approval :heavy_check_mark:

#171 Supplement README.md
  README.md
Labels: Enhancement, Two approvals :tada:

#170 Lava Puddles Map Debug
  lava_puddles/map.mts
Labels: Enhancement, One approval :heavy_check_mark:, Trivial

#172 Disable "Trouble in the Castle" map
  castle_trouble/map.conf
Labels: One approval :heavy_check_mark:

#173 Fix small bug in "Pyramids of Ahkmenrah" map
  ahkmenrah_pyramids/map.conf
  ahkmenrah_pyramids/map.mts
Labels: Bug / Bugfix, One approval :heavy_check_mark:

#176 Changes to Mini Village map
  mini_village/map.mts
  mini_village/screenshot.png
Labels: Enhancement, One approval :heavy_check_mark:

#151 Pine Forest map by mzf53
  pine_forest/map.conf
  pine_forest/map.mts
  pine_forest/screenshot.png
Labels: New map, Two approvals :tada:

#180 Add new "Water Academy" map
  water_academy/map.conf
  water_academy/map.mts
  water_academy/screenshot.png
Labels: New map, One approval :heavy_check_mark:

#184 README.md Changes
  README.md
Labels: Enhancement, One approval :heavy_check_mark:

#185 Add new "The Legend of Capturing" map by gameit
  capture_legend/map.conf
  capture_legend/map.mts
  capture_legend/screenshot.png
Labels: New map, One approval :heavy_check_mark:
