Repository MT-CTF/maps, pull requests merged in 2022-03, with the labels that each got.

#241 Abandoned Battlefield Update (CTFv3 update: 4 Teams Map)
  abandoned_battlefield/map.conf
  abandoned_battlefield/map.mts
  abandoned_battlefield/screenshot.png
Labels: Enhancement, Review required :mag:, Two approvals :tada:, v3Convert

#243 Abandoned Battlefield: Change red team to green team at savillis request
  abandoned_battlefield/map.conf
  abandoned_battlefield/map.mts
Labels: Two approvals :tada:

#242 Volcano сonversion to version 3.0
  volcano/map.conf
  volcano/map.mts
Labels: Enhancement, Review required :mag:, One approval :white_check_mark:, v3Convert
