Repository MT-CTF/maps, pull requests merged in 2022-07, with the labels that each got.

#229 New map "Water Academy"
  water_academy/map.conf
  water_academy/map.mts
  water_academy/screenshot.png
Labels: Enhancement, Review required :mag:, Two approvals :tada:, v3Convert

#245 Add new map "Dance of the Dragons"
  dragons_dance/map.conf
  dragons_dance/map.mts
  dragons_dance/screenshot.png
Labels: New map, Review required :mag:, Two approvals :tada:, v3Convert

#240 Sam's Mansion (Updated for v3)
  sams_mansion/map.conf
  sams_mansion/map.mts
  sams_mansion/skybox/Back.png
  sams_mansion/skybox/Down.png
  sams_mansion/skybox/Front.png
  sams_mansion/skybox/Left.png
  sams_mansion/skybox/Right.png
  sams_mansion/skybox/Up.png
Labels: Enhancement, Review required :mag:, One approval :white_check_mark:, v3Convert
