Repository MT-CTF/maps, pull requests merged in 2023-07, with the labels that each got.

#292 Give Lost Mountains Indestructible Red Barrier Stone for Underground
  lost_mountains/map.mts
Labels: Enhancement, Review required :mag:

#295 Update map.conf of Big Ocean (Revision of the chest zones)
  big_ocean/map.conf
Labels: Enhancement, Review required :mag:

#297 Iceage chests increase
  iceage/map.conf
Labels: Enhancement, One approval :white_check_mark:

#291 add ant war map
  ant_war/map.conf
  ant_war/map.mts
  ant_war/screenshot.png
Labels: New map, Review required :mag:, Two approvals :tada:

#276 Add new map "Appleton" by oMikekiMo
  appleton/map.conf
  appleton/map.mts
  appleton/screenshot.png
Labels: New map, Review required :mag:, Two approvals :tada:
